### ISSUE TITLE
Multiplayer-isometric-mouse

### ISSUE THREAD

**Issue by CLTanuki** [Irrelon/ige#435]
In example 24.5 there is bug on line 73 of CharacterContainer.js:

``` javascript
this._streamDir = this.path.currentDirection();
                                          ^
TypeError: this.path.currentDirection is not a function

```

UPD:

``` javascript
if (ige.isClient) {
      console.log('Client');
            // Listen for mouse events on the texture map
            ige.client.textureMap1.mouseUp(function (tileX, tileY, event) {
        console.log(tileX, tileY, event);
                // Send a message to the server asking to path to this tile
                ige.network.send('playerControlToTile', [tileX, tileY]);
            });
        }
```

In mouseUp event first var is actually event, third is null and second is:

``` javascript
Object {_cancelled: false}
_cancelled: false
stopPropagation: ()
arguments: null
caller: null
length: 0
name: ""
prototype: _eventControl.stopPropagation
__proto__: ()
<function scope>
__proto__: Object
```

Then server faults with ServerNetworkEvents.js:64

``` javascript
.path.add(newPath)
        ^
TypeError: Cannot read property 'add' of undefined
```

**Comment by CLTanuki** [comment]
UPD:
This code in PlayerComponent logs 'Client' to console but no tiles:
`if (ige.isClient) {
      console.log('Client');
			// Listen for mouse events on the texture map
			ige.client.textureMap1.mouseUp(function (tileX, tileY, event) {
        console.log(tileX, tileY, event);
				// Send a message to the server asking to path to this tile
				ige.network.send('playerControlToTile', [tileX, tileY]);
			});
		}`

**Comment by JacobPersi** [comment]
I'm in the process of trying to figure out what's going on. The issue seems to revolve around old code interacting with the path component in ServerNetworkEvents.js (_onPlayerControlToTile).

The error occurs because the clear, add, and start methods don't allow for chaining, but it seems as though the whole component is setup incorrectly.

**Comment by JacobPersi** [comment]
I've managed to get this working: [see my latest commit](https://github.com/JacobPersi/ige/commit/330dd9f08f6721970064f7bd94d1db56995e427c), however I've noticed that the mouse-up callback is only triggered if you click within the top 3 tiles. This is most likely because I'm using the wrong tile map or haven't properly set it's bounds... but unfortunately I don't have any more time tonight.

**Comment by matbht** [comment]
I don't know what you are building, but have a rest and good night.

Keep pushing
