### ISSUE TITLE
moderation not happening on forum

### ISSUE THREAD

**Issue by foobarbecue** [Irrelon/ige#460]
I made several posts on the forum at http://www.isogenicengine.com/forum/viewforum.php a couple of weeks ago, but none of them have been displayed because they are "awaiting moderation."

I was really excited about Isogenic and spent about 15 hours learning it. I made some cool simple test scenes, but it became clear that IGE sure has some issues. This wouldn't be such a big deal if there was some way to interact with other developers trying to use it. But since there's a forum which appears to just be sucking everyone's posts into a black hole... it's time to switch to Unity, I guess.

**Comment by ChrisEt** [comment]
I know what you mean man. I spent one and a half year using IGE and extending it here and there. But then I got the feeling I'm almost alone. You know, at several points in development you have to coordinate with the other developers: Is anybody else relying on this faulty behaviour, can we just change it, can we pull this functionality together in one module or is there a historic reasons for having it implemented in two modules, etc. I hardly received any responses. 
That's why I finally moved to Unity, even though its HTML capabilities were far behind at that time.

**Comment by ozznixon** [comment]
Some of the forks has made tremendous headway. I was one of those who
"bought" my IGE.

**Comment by Irrelon** [comment]
I'm sorry guys. Forum was getting spammed daily beyond belief so I switched it to moderated to try and stop the deluge. That of course requires that I moderate the queue every day manually :(

Just to answer other points as well: It is true that the engine did not reach a critical mass of users that would have helped to create a proper community around it. I had hoped that by open-sourcing the entire project that it would pick up a bit, but that was definitely wishful thinking.

I spent four years creating IGE from scratch by myself. This doesn't just mean the code but also the website, the "documentation", various painful refactors as HTML5 matured etc, and trying but failing to find a way to sustain the project financially. In the end the business model I put in place was a major failure. This all led to me having to take a real job again as I'd burned through all my savings and have a mortgage and kids.

Long story short, individual license sales is an unsustainable model if your software is a niche market product. In hindsight I should really have gone with a subscription model - but at the time the dev community was VERY hostile to that suggestion so there is no way to know if that would have had any better outcome. Probably, if I had some seed funding and was able to have created a fully-featured editor and excellent documentation, this *might* have pushed the project to critical mass.

As more and more of my time got pulled into sustaining my financial situation so I didn't go homeless, less and less of that time was able to go to the project I loved but wasn't paying any bills. That, ultimately is why Isogenic hasn't received any love for a long time.

There were some really great devs who tried to help out as Chris has mentioned, but you can also imagine the overhead of checking through PRs etc to integrate any third party code - it comes right back to time.

Unity now has a proper WebGL export capability and I believe UE4 does too (no idea what the runtime download size is on those but I'm guessing it will continue to improve anyway).

Sad fact of the whole thing is I can pretty-much place failure of this project down to three main reasons:

1) I was naive and came up with a really crappy business model that was doomed to fail because it was unsustainable, selling a lifetime license to a very small number of people.

2) I didn't know anyone else who had the time / wanted to help me to make the engine a success. One person CANNOT build a business by themselves (especially if you have a wife, kids and mortgage - probably possible if you are living in your parent's house with no commitments though). You need at least 2 people. I learnt that the hard way, trying to do everything myself and multi-failing.

3) Most devs on the web really don't want to pay for stuff, even if it represents multiple hundreds of hours of work - mostly because we've been spoilt over the years by tons of high quality free libraries, and I totally get that.

So I'm really sorry guys. Most of the failure of IGE is on me. My poor decisions in the business model, the lack of time to push forward in multiple directions like new code and new documentation, and my quickly evaporating savings account that was for the most part funding the whole thing. :(

**Comment by gdudding** [comment]
I still consider IGE the best Javascript game engine out there, it's handled everything I've thrown at it with elegance.  My challenges to complete my game are 100% art pipeline related, and there's no 2D engine that would make it any easier, so, I recoil a bit when you call it a "failed" project.  Commercially unsuccessful, maybe, but it's a great engine.

If you want my input for a good direction for the engine to go?  I'd integrate it with something like Meteor JS, to give easy app-making capability as well as account management backend tie-ins to mongo via meteor.

**Comment by ChrisEt** [comment]
Don't put all the blame on yourself! You created a great piece of software, which I would call quite revolutionary for that time. I have looked at several HTML5 engines and none was even half as mature and feature-rich. Be proud on what you created, not sad about what you didn't manage to. IGE contains some quite ingenious things such as the JS compressor/obfuscator, pre-loading of assets or the highly-sophisticated network synchronization.

In my opinion what IGE would have needed is a handful of commercially successful projects building upon it. That would have given it the required support in terms of developments and/or money. Such projects would have paid you maybe for extending IGE according to their needs. You are right, a comprehensive game engine is too big for one person to stem alone.

If I look at the big number of Flash-based games and the fact that Flash is slowly dying, I think the time of HTML5 games is yet to come. Maybe IGE was just a bit before its time!

**Comment by Irrelon** [comment]
Thanks guys for your kind words, and for your advice. I think you are both correct.

I am still spending some of my free time creating a game with IGE that will hopefully get finished and put online so people can enjoy it. From the requirements of that game (Starflight) the appCore branch was born so there are still some small updates here and there.

I guess I just feel bad because I really didn't want to let anyone down. Really appreciate the time you guys took to learn IGE and to use it which in turn grew the fledgling community. If nothing else the project was worth the time just to connect with some really great people like you guys. 👍

**Comment by JacobPersi** [comment]
Getting these email notifications because I used Isogenic for a freelance project a while back and had some issues... you're going to make me cry.

**Comment by ozznixon** [comment]
Hey take it with a stride ... I have been there, took on more than time
allows... especially with a successful product. I can offer my skills on
developing a custom forum, and hosting it (have servers across the US,EU
and Asia).

Based upon everyone's response - your product is great - and obviously
there are many willing to help - just ask these guys!

Ozz

**Comment by foobarbecue** [comment]
FIrst of all, I'm sorry for being impatient! My forum posts are now approved.

Thanks so much @Irrelon for your candid explanation of what's going on, and for giving this gift to the open source community. As far as I can tell there isn't a better engine out there for native javascript games. Unity compiles through asm.js from C / C++ . There's something to be said for being about to target javascript and the DOM directly.

**Comment by foobarbecue** [comment]
While I'm at it let me just mention that the space example game was super fun... in fact that was another obstacle to learning IGE, my brother and were trying to work on a game together but instead we kept playing that example game!

**Comment by raldred** [comment]
No need to be so hard on yourself Rob.
You've created an amazing product and I personally thoroughly enjoyed
working with it and contributing back where I could.
The games I created using IGE for BBC are still enjoyed by thousands of
children in each month. That's got to bring some sense of achievement right?

All the best
Rob

**Comment by Irrelon** [comment]
You guys rock. Maybe I shouldn't be so hard on myself but there really was no one else to blame for anything... since I was the only one working on the project lol. That said, there were some really cool games made, I think the two that stand out are @raldred BBC game and CasinoRPG which is still going strong too.

The positivity here almost gives me some renewed energy for IGE updates. Then I look at the mammoth task list. I think the best approach is for me to finish Starflight and open-source it. The code is well commented and documented and I suspect it would be a really great starting point for anyone looking to hack a game together. It has all the stuff you'd want, multiplayer, physics, 2d and isometric scenes, story lines, quests etc etc. 

![starflight-screeny](https://user-images.githubusercontent.com/492293/33948982-2a5d125e-e020-11e7-8a6f-20bca8b1796d.png)

**Comment by 7dolls** [comment]
Hi all, I personally think the engine is fantastic. I have been working with it on and off for years. I have also tried lots of other engines (mostly when I got fed up with something I could not understand or was not working on IGE), but have always come back to the best. There is a lot of stuff going on in the engine, a lot of which is missed unless you know JS. You need to have a good grasp on JS to implement it. I still think IGE is the Rolls Royce of isometric engines. If we all put our heads and code together we can raise the awareness and use of the engine.

**Comment by ozznixon** [comment]
I too agree! I am the neophyte of all of us, I have coded commercially for 35 years, but, zero game engine. I have developed a game server backend – but, have yet to move to the U/I side yet. Mainly, didn’t know where to start once I downloaded IGE. So, I would love to code the tutorials and demonstrations (with guidance).

**Comment by m0dE** [comment]
Hey Rob,
Mod Studio (modd.io) is still going strong. It's played by 10's of millions of people and new games are being created every day :) Your legacy will continue.

**Comment by Irrelon** [comment]
@m0dE I love braains.io!

**Comment by Zenchess** [comment]
Cannot log into forum, activated account but it won't let me log in.  Even did forgot password process and activated the new password, but still can't log in.

Was just going to ask if anyone knows how to do intelliSense in Visual Studio Code with isogenic.

Btw I have started using Isogenic again for a multiplayer asteroids style space game and it's amazing how easy it is with the built in networking to get everything going.  I wouldn't discount this engine, this is still the best =)

**Comment by Irrelon** [comment]
@Zenchess What username did you use on the forum I can activate it manually for you :)

I don't know about VS but in WebStorm you right click on the engine folder in the ige repo and select Mark Directory As -> Resource Root

Maybe there is something similar in VS?

**Comment by Zenchess** [comment]
Oh my bad, I kept trying to use my email instead of username to log in...

**Comment by ButsAndCats** [comment]
I think IGE is **the best html5 engine**. It does however have a much steeper learning curve due to the fact there is much of a community formed around it. Therefore less tutorials, less examples, less people to answer tricky questions.
I think a documentation ebook could make a lot of financial return and help break down that learning curve.

**Comment by RockManJoe64** [comment]
I just came across this engine, and am excited to try it out! I don't think it's too late to try and start a business around it. You can probably model something similar to what Phaser.js is doing!

**Comment by beyond-code-github** [comment]
I'm late to this party I know, but for anyone reading this please don't be put off. If you are looking to write an indie game, maybe it's your first one, this engine is GREAT!

The tutorials are excellent, and really do cover most of the bases. As an experienced programmer I've not found the lack of forums or blog posts to be much of an issue, because the source code is just so easy to read, it's well structured, well commented and if you're in doubt you can simply read through it and figure out what's supposed to be happening.

I am still working with it actively, and pushing the occasional bug fix that I find in as a PR, so my message here is don't overlook this engine just because of the status of the project, it's very well turned out and could even be considered feature complete for many types of game.

**Comment by m0dE** [comment]
has anyone had success implementing webGL/Pixi on isogenic engine?
